### ISSUE TITLE
Query using refs

### ISSUE THREAD

**Issue by kristian-puccio** [jquense/teaspoon#10]
A lot of react testing libraries allow you to query the dom using the refs.

Is this possible with teaspoon?

**Comment by jquense** [comment]
do you have an example of what you mean?

**Comment by kristian-puccio** [comment]
This is probably the best example of doing this.

https://github.com/QubitProducts/react-test-tree

**Comment by jquense** [comment]
nope, teaspoon takes a different approach to solving the same problem. Instead of adding refs to query the dom/tree you can just use css selectors. I personally find the css selector approach cleaner and easier than adding refs to everything you might want to render (it also lets you reach into components that you can't add refs to)

**Comment by kristian-puccio** [comment]
Fair enough, was hoping for both but probably not really needed.

Thanks!

**Comment by jquense** [comment]
For Posterity i thought I should post a pattern I use, that in hindsight is what you meant.

```
let Component = () => <div><span _tID='my-span'/> </div>

$(<Component />).render().find('[_tID="my-span"]')
```
