### ISSUE TITLE
$.fn.eq

### ISSUE THREAD

**Issue by jacobp100** [jquense/teaspoon#37]
Example,

```js
const $firstRow = $element.find('tr').eq(1);
$firstRow.find('td');
```

**Comment by jquense** [comment]
any more of repro? it's working for me in my simple attempts

**Comment by jacobp100** [comment]
Sorry, it was my mistake. I had an array, and it was using `Array.prototype.find`.

**Comment by jacobp100** [comment]
Although there is a feature request for $.fn.eq (it's in regular jQuery). ;)

**Comment by jquense** [comment]
there is `nth()` already I think that does waht you are thinking of yeah?

**Comment by jacobp100** [comment]
Looks like that will work! Documentation would be good.

Is the aim to get feature parity with jQuery? At the moment, I'm polyfilling the methods I need—is that something you'd be interested in merging when it's a bit more complete?

**Comment by jquense** [comment]
> Is the aim to get feature parity with jQuery?

Not really, in a lot of cases that wouldn't make any sense. I am open to PR's that add selection methods though if you want to contribute. We probably won't add everything since the goals of tsp are a bit more focused, which is why we try to make it easy to extend, but yeah if you have stuff you use all the time, i'll take PRs
